import { SITE } from "@/lib/site";

export default async function sitemap() {
  const ENTRIES = [
    ["/", "daily", 1.0],
    ["/services", "weekly", 0.9],
    ["/process", "weekly", 0.8],
    ["/routes", "weekly", 0.8],
    ["/air-ambulance-cost", "weekly", 0.9],
    ["/icu-vs-medical-escort", "weekly", 0.8],
    ["/bangkok-hospitals", "weekly", 0.8],
    ["/about", "weekly", 0.7],
    ["/gallery", "monthly", 0.6],
    ["/faq", "weekly", 0.8],
    ["/contact", "weekly", 0.9],
    ["/blog", "daily", 0.8],
    ["/blog/what-is-an-air-ambulance", "weekly", 0.7],
    ["/blog/air-ambulance-vs-commercial-medical-flight", "weekly", 0.7],
    ["/blog/emergency-medical-evacuation-dhaka-to-bangkok", "weekly", 0.7],
    ["/blog/why-bangladeshi-patients-choose-bangkok", "weekly", 0.7],
    ["/blog/medical-repatriation-to-bangladesh", "weekly", 0.7],
    ["/blog/air-ambulance-dhaka-bangkok-bumrungrad-cost", "weekly", 0.7],
    ["/blog/what-to-expect-dhaka-bumrungrad-air-ambulance", "weekly", 0.7],
    ["/cardiac-emergency-transfer", "weekly", 0.8],
    ["/stroke-neurology-evacuation", "weekly", 0.8],
    ["/cancer-treatment-bangkok", "weekly", 0.8],
    ["/trauma-accident-evacuation", "weekly", 0.8],
    ["/insurance-coverage", "weekly", 0.7],
    ["/blog/icu-flight-bangladesh-to-bumrungrad-bangkok", "weekly", 0.7],
    ["/blog/air-ambulance-insurance-payment-dhaka-bumrungrad", "weekly", 0.7],
    ["/blog/bangkok-hospital-admission-bangladeshi-patients", "weekly", 0.7],
    ["/blog/how-to-book-air-ambulance-dhaka-bumrungrad", "weekly", 0.7],
    ["/blog/stroke-air-ambulance-dhaka-bumrungrad", "weekly", 0.7],
    ["/author/tawhid-iqbal", "monthly", 0.5],
    ["/privacy", "monthly", 0.3],
    ["/terms", "monthly", 0.3],
    ["/guides/air-ambulance-dhaka-bangkok", "monthly", 0.9],
    ["/guides/icu-air-ambulance-dhaka", "monthly", 0.9],
    ["/blog/bed-to-bed-transfer-dhaka-bangkok", "weekly", 0.7],
    ["/blog/emergency-air-ambulance-when-to-call", "weekly", 0.7],
    ["/blog/air-ambulance-cardiac-patients", "weekly", 0.7],
    ["/blog/bangkok-hospitals-comparison-bangladeshi-patients", "weekly", 0.7],
    ["/blog/admit-patient-bumrungrad-dhaka-guide", "weekly", 0.7],
    ["/blog/neonatal-pediatric-air-ambulance-dhaka-bangkok", "weekly", 0.7],
    ["/blog/medical-visa-thailand-for-bangladeshi-patients", "weekly", 0.7],
    ["/blog/air-ambulance-dhaka-to-india-vellore-chennai-delhi", "weekly", 0.8],
    ["/blog/dialysis-patient-air-ambulance-dhaka-bangkok", "weekly", 0.8],
    ["/blog/liver-disease-air-ambulance-dhaka-bangkok", "weekly", 0.8],
    ["/blog/air-ambulance-cost-bangladesh-2026", "weekly", 0.7],
    ["/blog/bumrungrad-international-hospital-dhaka-guide", "weekly", 0.7],
    ["/blog/medical-tourism-thailand-bangladesh", "weekly", 0.7],
    ["/blog/post-surgery-patient-transfer-dhaka", "weekly", 0.7],
    ["/blog/ventilator-patient-air-ambulance", "weekly", 0.7],
    ["/blog/air-ambulance-dhaka-to-singapore", "weekly", 0.8],
  ];

  return ENTRIES.map(([urlPath, changeFrequency, priority]) => ({
    url: `${SITE.baseUrl}${urlPath}`,
    changeFrequency,
    priority,
  }));
}
